---
- name: Starting mariadb container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ mariadb_image_full }}"
    name: "mariadb"
    volumes: "{{ node_config_directory }}/mariadb/:{{ container_config_directory }}/:ro"
    volumes_from: "mariadb_data"
  when: delegate_host != 'None' or
        ( groups['mariadb'] | length ) == 1 or
        ( delegate_host == 'None' and inventory_hostname != groups['mariadb'][0] )
