---
- name: Starting MariaDB container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    net: host
    pull: "{{ docker_pull_policy }}"
    restart_policy: "{{ docker_restart_policy }}"
    restart_policy_retry: "{{ docker_restart_policy_retry }}"
    state: reloaded
    registry: "{{ docker_registry }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
    insecure_registry: "{{ docker_insecure_registry }}"
    name: mariadb
    image: "{{ mariadb_image_full }}"
    volumes: "{{ node_config_directory }}/mariadb/:/opt/kolla/config_files/:ro"
    volumes_from:
      - "mariadb_data"
    env:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
  when: delegate_host != 'None' or
        ( groups['mariadb'] | length ) == 1 or
        ( delegate_host == 'None' and inventory_hostname != groups['mariadb'][0] )
