---
- include: config.yml

- include: bootstrap.yml

- include: start.yml

- include: register.yml

# This will restart the container we initially used to bootstrap the cluster to
# make it match the other containers environment-wise. This also prevents a
# change from showing up when rerunning the playbooks
- include: start.yml
