---
- name: Ensuring config directory exists
  file:
    path: "{{ node_config_directory }}/memcached/"
    state: "directory"
    recurse: "yes"

- name: Copying over memcached JSON configuration file
  template:
    src: "memcached.json.j2"
    dest: "{{ node_config_directory }}/memcached/config.json"
