---
- name: Creating the Glance service and endpoint
  kolla_keystone_service:
    service_name: "glance"
    service_type: "image"
    description: "Openstack Image"
    endpoint_region: "{{ openstack_region_name }}"
    admin_url: "http://{{ kolla_internal_address }}:{{ glance_api_port }}"
    internal_url: "http://{{ kolla_internal_address }}:{{ glance_api_port }}"
    public_url: "http://{{ kolla_external_address }}:{{ glance_api_port }}"
    auth: "{{ openstack_auth_v2 }}"
    region_name: "{{ openstack_region_name }}"

- name: Creating the Glance project, user, and role
  kolla_keystone_user:
    project: "service"
    user: "glance"
    password: "{{ glance_keystone_password }}"
    role: "admin"
    auth: "{{ openstack_auth_v2 }}"
    region_name: "{{ openstack_region_name }}"
