---
- name: Starting Keystone container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    net: host
    pull: "{{ docker_pull_policy }}"
    restart_policy: "{{ docker_restart_policy }}"
    restart_policy_retry: "{{ docker_restart_policy_retry }}"
    state: reloaded
    registry: "{{ docker_registry }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
    insecure_registry: "{{ docker_insecure_registry }}"
    name: keystone
    image: "{{ keystone_image_full }}"
    volumes:
      - "{{ node_config_directory }}/keystone/:{{ container_config_directory }}/:ro"
      - "/var/lib/kolla/dev/log:/dev/log"
    env:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
