---
- include: ../../start.yml
  vars:
    container_environment:
      CONFIG_STRATEGY: "{{ config_strategy }}"
    container_image: "{{ docker_keystone_image_full }}"
    container_name: "keystone"
    container_volumes:
      - "{{ node_config_directory }}/keystone/:/opt/kolla/configs/keystone/:ro"
