---
- name: Starting keystone container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ keystone_image_full }}"
    name: "keystone"
    volumes:
      - "{{ node_config_directory }}/keystone/:{{ container_config_directory }}/:ro"
      - "rsyslog_socket:/var/lib/kolla/rsyslog/"

- name: Wait for keystone startup
  wait_for: host={{ keystone_admin_address }} port={{ keystone_admin_port }}
