---
- name: Starting ceph-mon container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ ceph_mon_image_full }}"
    name: "ceph_mon"
    volumes: "{{ node_config_directory }}/ceph-mon/:{{ container_config_directory }}/:ro"
    volumes_from: "ceph_mon_data"
  when: inventory_hostname in groups['ceph-mon']
