---
- name: Looking up OSDs for Ceph
  find_disks:
      partition_name: 'KOLLA_CEPH_DATA'
  register: osds

- name: Mounting Ceph OSD volumes
  mount:
    src: "UUID={{ item.fs_uuid }}"
    fstype: xfs
    state: mounted
    name: "/var/lib/ceph/osd/{{ item.fs_uuid }}"
  with_items: osds.disks

- name: Gathering OSD IDs
  command: 'cat /var/lib/ceph/osd/{{ item.fs_uuid }}/whoami'
  with_items: osds.disks
  register: id
  changed_when: False
  failed_when: id.rc != 0

- name: Starting ceph-osds container
  docker:
    tty: True
    net: host
    pull: "{{ docker_pull_policy }}"
    restart_policy: "{{ docker_restart_policy }}"
    restart_policy_retry: "{{ docker_restart_policy_retry }}"
    state: reloaded
    registry: "{{ docker_registry }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
    insecure_registry: "{{ docker_insecure_registry }}"
    pid: host
    privileged: True
    name: "ceph_osd_{{ item.0.stdout }}"
    image: "{{ ceph_osd_image_full }}"
    volumes:
      - "/var/lib/ceph/osd/{{ item.1.fs_uuid }}:/var/lib/ceph/osd/ceph-{{ item.0.stdout }}"
      - "{{ node_config_directory }}/ceph-osd/:{{ container_config_directory }}/:ro"
      - "/dev/:/dev/"
    env:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
      OSD_ID: "{{ item.0.stdout }}"
      OSD_DEV: "{{ item.1.device }}"
  with_together:
    - id.results
    - osds.disks
  when: inventory_hostname in groups['ceph-osd']
        and osds.disks
