---
- name: Ensuring config directory exists
  file:
    path: "{{ node_config_directory }}/horizon/"
    state: "directory"
    recurse: "yes"

- name: Copying over config(s)
  template:
    src: "horizon.conf.j2"
    dest: "{{ node_config_directory }}/horizon/horizon.conf"

- name: Copying over config(s)
  template:
    src: "local_settings.j2"
    dest: "{{ node_config_directory }}/horizon/local_settings"
