---
- include: ../../config.yml
  vars:
    service_name: "nova-api"
    config_source:
      - "roles/{{ project_name }}/templates/nova.conf.j2"
      - "/etc/kolla/config/global.conf"
      - "/etc/kolla/config/database.conf"
      - "/etc/kolla/config/messaging.conf"
      - "/etc/kolla/config/{{ project_name }}.conf"
      - "/etc/kolla/config/{{ project_name }}/{{ service_name }}.conf"
    config_template_dest:
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_minimal"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_global"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_database"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_messaging"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_augment"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ service_name }}.conf_augment"
    config_dest: "{{ node_config_directory }}/{{ service_name }}/nova.conf"
  when: inventory_hostname in groups['nova-api']

- name: Copying Nova API JSON configuration file
  template:
    src: "roles/nova/templates/nova-api.json.j2"
    dest: "{{ node_config_directory }}/nova-api/config.json"

- include: ../../config.yml
  vars:
    service_name: "nova-conductor"
    config_source:
      - "roles/{{ project_name }}/templates/nova.conf.j2"
      - "/etc/kolla/config/global.conf"
      - "/etc/kolla/config/database.conf"
      - "/etc/kolla/config/messaging.conf"
      - "/etc/kolla/config/{{ project_name }}.conf"
      - "/etc/kolla/config/{{ project_name }}/{{ service_name }}.conf"
    config_template_dest:
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_minimal"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_global"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_database"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_messaging"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_augment"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ service_name }}.conf_augment"
    config_dest: "{{ node_config_directory }}/{{ service_name }}/nova.conf"
  when: inventory_hostname in groups['nova-conductor']

- name: Copying Nova Conductor JSON configuration file
  template:
    src: "roles/nova/templates/nova-conductor.json.j2"
    dest: "{{ node_config_directory }}/nova-conductor/config.json"

- include: ../../config.yml
  vars:
    service_name: "nova-consoleauth"
    config_source:
      - "roles/{{ project_name }}/templates/nova.conf.j2"
      - "/etc/kolla/config/global.conf"
      - "/etc/kolla/config/database.conf"
      - "/etc/kolla/config/messaging.conf"
      - "/etc/kolla/config/{{ project_name }}.conf"
      - "/etc/kolla/config/{{ project_name }}/{{ service_name }}.conf"
    config_template_dest:
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_minimal"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_global"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_database"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_messaging"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_augment"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ service_name }}.conf_augment"
    config_dest: "{{ node_config_directory }}/{{ service_name }}/nova.conf"
  when: inventory_hostname in groups['nova-consoleauth']

- name: Copying Nova Consoleauth JSON configuration file
  template:
    src: "roles/nova/templates/nova-consoleauth.json.j2"
    dest: "{{ node_config_directory }}/nova-consoleauth/config.json"

- include: ../../config.yml
  vars:
    service_name: "nova-scheduler"
    config_source:
      - "roles/{{ project_name }}/templates/nova.conf.j2"
      - "/etc/kolla/config/global.conf"
      - "/etc/kolla/config/database.conf"
      - "/etc/kolla/config/messaging.conf"
      - "/etc/kolla/config/{{ project_name }}.conf"
      - "/etc/kolla/config/{{ project_name }}/{{ service_name }}.conf"
    config_template_dest:
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_minimal"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_global"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_database"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_messaging"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_augment"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ service_name }}.conf_augment"
    config_dest: "{{ node_config_directory }}/{{ service_name }}/nova.conf"
  when: inventory_hostname in groups['nova-scheduler']

- name: Copying Nova Scheduler JSON configuration file
  template:
    src: "roles/nova/templates/nova-scheduler.json.j2"
    dest: "{{ node_config_directory }}/nova-scheduler/config.json"

- include: ../../config.yml
  vars:
    service_name: "nova-compute"
    config_source:
      - "roles/{{ project_name }}/templates/nova.conf.j2"
      - "/etc/kolla/config/global.conf"
      - "/etc/kolla/config/database.conf"
      - "/etc/kolla/config/messaging.conf"
      - "/etc/kolla/config/{{ project_name }}.conf"
      - "/etc/kolla/config/{{ project_name }}/{{ service_name }}.conf"
    config_template_dest:
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_minimal"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_global"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_database"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_messaging"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_augment"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ service_name }}.conf_augment"
    config_dest: "{{ node_config_directory }}/{{ service_name }}/nova.conf"
  when: inventory_hostname in groups['compute']

- name: Copying Nova Compute JSON configuration file
  template:
    src: "roles/nova/templates/nova-compute.json.j2"
    dest: "{{ node_config_directory }}/nova-compute/config.json"

- include: ../../config.yml
  vars:
    service_name: "nova-novncproxy"
    config_source:
      - "roles/{{ project_name }}/templates/nova.conf.j2"
      - "/etc/kolla/config/global.conf"
      - "/etc/kolla/config/database.conf"
      - "/etc/kolla/config/messaging.conf"
      - "/etc/kolla/config/{{ project_name }}.conf"
      - "/etc/kolla/config/{{ project_name }}/{{ service_name }}.conf"
    config_template_dest:
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_minimal"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_global"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_database"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_messaging"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_augment"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ service_name }}.conf_augment"
    config_dest: "{{ node_config_directory }}/{{ service_name }}/nova.conf"
  when: inventory_hostname in groups['nova-novncproxy']

- name: Copying Nova Novncproxy JSON configuration file
  template:
    src: "roles/nova/templates/nova-novncproxy.json.j2"
    dest: "{{ node_config_directory }}/nova-novncproxy/config.json"

- name: Copying Nova Libvirt JSON configuration file
  template:
    src: "roles/nova/templates/nova-libvirt.json.j2"
    dest: "{{ node_config_directory }}/nova-libvirt/config.json"
