---
- include: ../../start.yml
  vars:
    container_environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
    container_image: "{{ docker_nova_libvirt_image_full }}"
    container_name: "nova_libvirt"
    container_privileged: "True"
    container_pid: "True"
    container_volumes:
      - "/run:/run"
      - "/lib/modules:/lib/modules:ro"
      - "/var/lib/nova/instances"
  when: inventory_hostname in groups['compute']

- include: ../../start.yml
  vars:
    container_environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
    container_image: "{{ docker_nova_api_image_full }}"
    container_name: "nova_api"
    container_privileged: "True"
    container_volumes:
      - "{{ node_config_directory }}/nova-api/:/opt/kolla/nova-api/:ro"
      - "/lib/modules:/lib/modules:ro"
  when: inventory_hostname in groups['nova-api']

- include: ../../start.yml
  vars:
    container_environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
    container_image: "{{ docker_nova_conductor_image_full }}"
    container_name: "nova_conductor"
    container_volumes:
      - "{{ node_config_directory }}/nova-conductor/:/opt/kolla/nova-conductor/:ro"
  when: inventory_hostname in groups['nova-conductor']

- include: ../../start.yml
  vars:
    container_environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
    container_image: "{{ docker_nova_consoleauth_image_full }}"
    container_name: "nova_consoleauth"
    container_volumes:
      - "{{ node_config_directory }}/nova-consoleauth/:/opt/kolla/nova-consoleauth/:ro"
  when: inventory_hostname in groups['nova-consoleauth']

- include: ../../start.yml
  vars:
    container_environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
    container_image: "{{ docker_nova_novncproxy_image_full }}"
    container_name: "nova_novncproxy"
    container_volumes:
      - "{{ node_config_directory }}/nova-novncproxy/:/opt/kolla/nova-novncproxy/:ro"
  when: inventory_hostname in groups['nova-novncproxy']

- include: ../../start.yml
  vars:
    container_environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
    container_image: "{{ docker_nova_scheduler_image_full }}"
    container_name: "nova_scheduler"
    container_volumes:
      - "{{ node_config_directory }}/nova-scheduler/:/opt/kolla/nova-scheduler/:ro"
  when: inventory_hostname in groups['nova-scheduler']

- include: ../../start.yml
  vars:
    container_environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
    container_image: "{{ docker_nova_compute_image_full }}"
    container_name: "nova_compute"
    container_privileged: "True"
    container_volumes:
      - "{{ node_config_directory }}/nova-compute/:/opt/kolla/nova-compute/:ro"
      - "/run:/run"
      - "/lib/modules:/lib/modules:ro"
    container_volumes_from:
      - "nova_libvirt"
  when: inventory_hostname in groups['compute']
