---
- name: Starting rsyslog container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ rsyslog_image_full }}"
    name: "rsyslog"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/rsyslog/:{{ container_config_directory }}/:ro"
      - "rsyslog:/var/log"
      - "/run/kolla/:/run/kolla/"

- name: Starting kolla-toolbox container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    environment:
      ANSIBLE_NOCOLOR: "1"
      ANSIBLE_LIBRARY: "/usr/share/ansible"
    image: "{{ ansible_image_full }}"
    name: "kolla_toolbox"
    privileged: True
    volumes:
      - "/dev/:/dev/"
      - "/run/:/run/"
      - "/run/kolla/log:/dev/log"
