---
- include: ../../start.yml
  vars:
    container_command: "/bin/sleep infinity"
    container_environment:
      ANSIBLE_NOCOLOR: "1"
      ANSIBLE_LIBRARY: "/usr/share/ansible"
    container_image: "{{ docker_ansible_image_full }}"
    container_name: "kolla_ansible"
