---
- name: Ensuring config directory exists
  file:
    path: "{{ node_config_directory }}/rabbitmq/"
    state: "directory"
    recurse: "yes"

- name: Copying over config(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
     - { src: "rabbitmq-env.conf.j2",
         dest: "{{ node_config_directory }}/rabbitmq/rabbitmq-env.conf" }
     - { src: "rabbitmq.config.j2",
         dest: "{{ node_config_directory }}/rabbitmq/rabbitmq.config" }

- name: Copying Rabbitmq JSON configuration file
  template:
    src: "roles/rabbitmq/templates/rabbitmq.json.j2"
    dest: "{{ node_config_directory }}/rabbitmq/config.json"