---
- include: ../../config.yml
  vars:
    service_name: "murano-engine"
    config_source:
      - "roles/{{ project_name }}/templates/murano.conf.j2"
      - "/etc/kolla/config/global.conf"
      - "/etc/kolla/config/database.conf"
      - "/etc/kolla/config/messaging.conf"
      - "/etc/kolla/config/{{ project_name }}.conf"
      - "/etc/kolla/config/{{ project_name }}/{{ service_name }}.conf"
    config_template_dest:
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_minimal"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_global"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_database"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_messaging"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_augment"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ service_name }}.conf_augment"
    config_dest: "{{ node_config_directory }}/{{ service_name }}/murano.conf"
  when: inventory_hostname in groups['murano-engine']

- include: ../../config.yml
  vars:
    service_name: "murano-api"
    config_source:
      - "roles/{{ project_name }}/templates/murano.conf.j2"
      - "/etc/kolla/config/global.conf"
      - "/etc/kolla/config/database.conf"
      - "/etc/kolla/config/messaging.conf"
      - "/etc/kolla/config/{{ project_name }}.conf"
      - "/etc/kolla/config/{{ project_name }}/{{ service_name }}.conf"
    config_template_dest:
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_minimal"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_global"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_database"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_messaging"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ project_name }}.conf_augment"
      - "{{ node_templates_directory }}/{{ service_name }}/{{ service_name }}.conf_augment"
    config_dest: "{{ node_config_directory }}/{{ service_name }}/murano.conf"
  when: inventory_hostname in groups['murano-api']
