---
- name: Ensuring config directory exists
  file:
    path: "{{ node_config_directory }}/haproxy/"
    state: "directory"
    recurse: "yes"

- name: Copying over config(s)
  template:
    src: "haproxy.cfg.j2"
    dest: "{{ node_config_directory }}/haproxy/haproxy.cfg"

- name: Copying haproxy JSON configuration file
  template:
    src: "haproxy.json.j2"
    dest: "{{ node_config_directory }}/haproxy/config.json"

- name: Allowing non-local IP binding
  sysctl: name="net.ipv4.ip_nonlocal_bind" value=1 sysctl_set=yes
  when: set_sysctl | bool

- name: Ensuring config directory exists
  file:
    path: "{{ node_config_directory }}/keepalived/"
    state: "directory"
    recurse: "yes"

- name: Copying keepalived JSON configuration file
  template:
    src: "keepalived.json.j2"
    dest: "{{ node_config_directory }}/keepalived/config.json"

- name: Copying over config(s)
  template:
    src: "keepalived.conf.j2"
    dest: "{{ node_config_directory }}/keepalived/keepalived.conf"
