---
- name: Starting keepalived container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    net: host
    pull: "{{ docker_pull_policy }}"
    restart_policy: "{{ docker_restart_policy }}"
    restart_policy_retry: "{{ docker_restart_policy_retry }}"
    state: reloaded
    registry: "{{ docker_registry }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
    insecure_registry: "{{ docker_insecure_registry }}"
    name: keepalived
    image: "{{ keepalived_image_full }}"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/keepalived/:{{ container_config_directory }}/:ro"
      - "/run:/run"
      - "/lib/modules:/lib/modules:ro"
    env:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"

- name: Starting HAProxy container
  docker:
    docker_api_version: "{{ docker_api_version }}"
    net: host
    pull: "{{ docker_pull_policy }}"
    restart_policy: "{{ docker_restart_policy }}"
    restart_policy_retry: "{{ docker_restart_policy_retry }}"
    state: reloaded
    registry: "{{ docker_registry }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
    insecure_registry: "{{ docker_insecure_registry }}"
    name: haproxy
    image: "{{ haproxy_image_full }}"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/haproxy/:{{ container_config_directory }}/:ro"
      - "/run:/run"
    env:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"

- name: Ensuring latest haproxy config is used
  command: docker exec haproxy /usr/local/bin/kolla_ensure_haproxy_latest_config
  register: status
  changed_when: status.stdout.find('changed') != -1

- name: Waiting for virtual IP to appear
  wait_for: host="{{ kolla_internal_address }}" port="{{ mariadb_port }}"
