---
- include: ../../start.yml
  vars:
    container_image: "{{ docker_keepalived_image_full }}"
    container_name: "keepalived"
    container_privileged: "True"
    container_volumes:
      - "{{ node_config_directory }}/keepalived/:/opt/kolla/keepalived/:ro"
      - "/run:/run"
    container_environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"

- include: ../../start.yml
  vars:
    container_image: "{{ docker_haproxy_image_full }}"
    container_name: "haproxy"
    container_volumes:
      - "{{ node_config_directory }}/haproxy/:/opt/kolla/haproxy/:ro"
      - "/run:/run"
    container_environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"

- name: Ensuring latest haproxy config is used
  command: docker exec haproxy /opt/kolla/ensure_latest_config.sh
  register: status
  changed_when: status.stdout.find('changed') != -1
