---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "searchlight-api"
    - "searchlight-listener"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "searchlight-api"
    - "searchlight-listener"

- name: Copying over searchlight.conf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/searchlight.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/messaging.conf"
      - "{{ node_custom_config }}/searchlight.conf"
      - "{{ node_custom_config }}/searchlight/{{ inventory_hostname }}/searchlight.conf"
    dest: "{{ node_config_directory }}/{{ item }}/searchlight.conf"
  with_items:
    - "searchlight-api"
    - "searchlight-listener"
