desiredState:
  manifest:
    containers:
    - env:
      - name: ZAQAR_DB_PASSWORD
        value: password
      - name: ZAQAR_KEYSTONE_PASSWORD
        value: password
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: kollaglue/fedora-rdo-zaqar
      name: zaqar-server
      ports:
      - containerPort: 8004
    id: zaqar-1
    version: v1beta1
id: zaqar
labels:
  name: zaqar
