---
- name: Ensuring config directory exists
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
  with_items:
    - "cinder-volume"
    - "cinder-backup"
  when: inventory_hostname in groups['cinder-volume']

- name: Copying over config(s)
  template:
    src: roles/ceph/templates/ceph.conf.j2
    dest: "{{ node_config_directory }}/{{ item }}/ceph.conf"
  with_items:
    - "cinder-volume"
    - "cinder-backup"
  when: inventory_hostname in groups['cinder-volume']

# TODO(SamYaple): Improve failed_when and changed_when tests
- name: Creating ceph pool for cinder
  command: docker exec ceph_mon ceph osd pool create volumes 128 {{ ceph_pool_type }}
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  changed_when: False
  failed_when: False
  run_once: True

# TODO(SamYaple): Improve failed_when and changed_when tests
- name: Creating ceph pool for cinder-backup
  command: docker exec ceph_mon ceph osd pool create backups 128 {{ ceph_pool_type }}
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  changed_when: False
  failed_when: False
  run_once: True

# TODO(SamYaple): Improve failed_when and changed_when tests
- name: Pulling cephx keyring for cinder
  command: docker exec ceph_mon ceph auth get-or-create client.cinder mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rx pool=images'
  register: cephx_key_cinder
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  changed_when: False
  run_once: True

# TODO(SamYaple): Improve failed_when and changed_when tests
- name: Pulling cephx keyring for cinder-backup
  command: docker exec ceph_mon ceph auth get-or-create client.cinder-backup mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=backups'
  register: cephx_key_cinder_backup
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  changed_when: False
  run_once: True

- name: Pushing cephx keyring
  copy:
    content: "{{ item.content }}\n\r"
    dest: "{{ node_config_directory }}/{{ item.service_name }}/ceph.client.{{ item.key_name }}.keyring"
    mode: "0600"
  with_items:
    - { service_name: "cinder-volume", key_name: "cinder", content: "{{ cephx_key_cinder.stdout }}" }
    - { service_name: "cinder-backup", key_name: "cinder-backup", content: "{{ cephx_key_cinder_backup.stdout }}" }
  when: inventory_hostname in groups['cinder-volume']
