---
- hosts: database
  roles:
    - database
  tags: database

- hosts: message-broker
  roles:
    - message-broker
  tags: message-broker

- hosts: keystone
  roles:
    - keystone
  tags: keystone
