---
- hosts: haproxy
  roles:
    - haproxy
  tags: haproxy

- hosts: mariadb
  roles:
    - mariadb
  tags: mariadb

- hosts: rabbitmq
  roles:
    - rabbitmq
  tags: rabbitmq

- hosts: keystone
  roles:
    - keystone
  tags: keystone

- hosts: glance
  roles:
    - glance
  tags: glance

- hosts:
    - nova
    - compute
  roles:
    - nova
  tags: nova

- hosts:
    - neutron
    - compute
  roles:
    - neutron
  tags: neutron
