---
- hosts: database
  roles:
    - database
  tags: database

- hosts: message-broker
  roles:
    - message-broker
  tags: message-broker

- hosts: keystone
  roles:
    - keystone
  tags: keystone

- hosts: glance
  roles:
    - glance
  tags: glance

- hosts:
    - nova
    - compute
  roles:
    - nova
  tags: nova

- hosts:
    - neutron
    - compute
  roles:
    - neutron
  tags: neutron
