---
- hosts:
    - ceph-mon
    - ceph-osd
    - ceph-rgw
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: ceph,
        tags: ceph,
        when: enable_ceph | bool }

- hosts: collectd
  roles:
    - { role: collectd,
        tags: collectd,
        when: enable_collectd | bool }

- hosts: elasticsearch
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: elasticsearch,
        tags: elasticsearch,
        when: enable_elasticsearch | bool }

- hosts: influxdb
  roles:
    - { role: influxdb,
        tags: influxdb,
        when: enable_influxdb | bool }

- hosts: haproxy
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: haproxy,
        tags: haproxy,
        when: enable_haproxy | bool }

- hosts: kibana
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: kibana,
        tags: kibana,
        when: enable_kibana | bool }

- hosts: memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: memcached,
        tags: [memcache, memcached],
        when: enable_memcached | bool }

- hosts: mariadb
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: mariadb,
        tags: mariadb,
        when: enable_mariadb | bool }

- hosts:
    - iscsid
    - tgtd
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: iscsi,
        tags: iscsi,
        when: enable_cinder_backend_lvm | bool }

- hosts:
    - multipathd
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: multipathd,
        tags: multipathd,
        when: enable_multipathd | bool }

- hosts: rabbitmq
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: rabbitmq,
        tags: rabbitmq,
        when: enable_rabbitmq | bool }

- hosts:
    - keystone
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: keystone,
        tags: keystone,
        when: enable_keystone | bool }

- hosts:
    - swift-account-server
    - swift-container-server
    - swift-object-server
    - swift-proxy-server
    - rabbitmq
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: swift,
        tags: swift,
        when: enable_swift | bool }

- hosts:
    - ceph-mon
    - glance-api
    - glance-registry
    - rabbitmq
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: glance,
        tags: glance,
        when: enable_glance | bool }

- hosts:
    - ceph-mon
    - compute
    - glance-api
    - nova-api
    - nova-conductor
    - nova-consoleauth
    - nova-novncproxy
    - nova-scheduler
    - rabbitmq
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: nova,
        tags: nova,
        when: enable_nova | bool }

# (gmmaha): Please do not change the order listed here. The current order is a
# workaround to fix the bug https://bugs.launchpad.net/kolla/+bug/1546789
- hosts:
    - neutron-server
    - neutron-dhcp-agent
    - neutron-l3-agent
    - neutron-lbaas-agent
    - neutron-metadata-agent
    - compute
    - manila-share
    - rabbitmq
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: neutron,
        tags: neutron,
        when: enable_neutron | bool }

- hosts:
    - ceph-mon
    - cinder-api
    - cinder-backup
    - cinder-scheduler
    - cinder-volume
    - rabbitmq
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: cinder,
        tags: cinder,
        when: enable_cinder | bool }

- hosts:
    - heat-api
    - heat-api-cfn
    - heat-engine
    - rabbitmq
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: heat,
        tags: heat,
        when: enable_heat | bool }

- hosts:
    - horizon
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: horizon,
        tags: horizon,
        when: enable_horizon | bool }

- hosts:
    - murano-api
    - murano-engine
    - rabbitmq
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: murano,
        tags: murano,
        when: enable_murano | bool }

- hosts:
    - ironic-api
    - ironic-conductor
    - ironic-inspector
    - ironic-pxe
    - rabbitmq
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: ironic,
        tags: ironic,
        when: enable_ironic | bool }

- hosts:
    - magnum-api
    - magnum-conductor
    - rabbitmq
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: magnum,
        tags: magnum,
        when: enable_magnum | bool }

- hosts:
    - mistral-api
    - mistral-engine
    - mistral-executor
    - rabbitmq
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: mistral,
        tags: mistral,
        when: enable_mistral | bool }

- hosts:
    - sahara-api
    - sahara-engine
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: sahara,
        tags: sahara,
        when: enable_sahara | bool }

- hosts:
    - mongodb
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: mongodb,
        tags: mongodb,
        when: enable_mongodb | bool }

- hosts:
    - manila-api
    - manila-share
    - manila-scheduler
    - rabbitmq
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: manila,
        tags: manila,
        when: enable_manila | bool }

- hosts:
    - gnocchi-api
    - gnocchi-metricd
    - gnocchi-statsd
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: gnocchi,
        tags: gnocchi,
        when: enable_gnocchi | bool }

- hosts:
    - ceilometer
    - compute
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: ceilometer,
        tags: ceilometer,
        when: enable_ceilometer | bool }

- hosts:
    - aodh
    - rabbitmq
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: aodh,
        tags: aodh,
        when: enable_aodh | bool }

- hosts:
    - barbican-api
    - barbican-keystone-listener
    - barbican-worker
  roles:
    - { role: barbican,
        tags: barbican,
        when: enable_barbican | bool }

- hosts:
    - congress-api
    - congress-policy-engine
    - congress-datasource
    - rabbitmq
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: congress,
        tags: congress,
        when: enable_congress | bool }

- hosts:
    - tempest
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: tempest,
        tags: tempest,
        when: enable_tempest | bool }

- hosts: rally
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: rally,
        tags: rally,
        when: enable_rally | bool }

- hosts:
    - watcher-api
    - watcher-engine
    - watcher-applier
    - rabbitmq
    - memcached
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: watcher,
        tags: watcher,
        when: enable_watcher | bool }

- hosts:
    - cloudkitty-api
    - cloudkitty-processor
  serial: '{{ "30%" if action == "upgrade" else "0" }}'
  roles:
    - { role: cloudkitty,
        tags: cloudkitty,
        when: enable_cloudkitty | bool }
